#! /bin/bash

file=$1

if [ -z "$file" ] ; then
  echo "usage: setup_grub image_file"
  exit 1
fi

mnt $file
sw 0 mkdir -p /mnt/boot/grub
sw 0 cp /usr/lib/grub/{fat_stage1_5,stage1,stage2} /mnt/boot/grub
sw 0 cp /boot/vmlinuz /boot/initrd /boot/message /mnt/boot

sw 0 sh -c 'cat >/mnt/boot/grub/menu.lst' <<zap
default 0
timeout 20
gfxmenu (hd0,0)/boot/message

title Test 1
  root (hd0,0)
  kernel /boot/vmlinuz vga=0x314 splash=silent showopts
  initrd /boot/initrd

title Test 2
  root (hd0,0)
  kernel /boot/vmlinuz vga=0x314 splash=silent showopts
  initrd /boot/initrd
zap

umnt

echo -e "device (hd0) /mnt/boot.img\nsetup --prefix=/boot/grub (hd0) (hd0,0)" | sw 0 grub --batch

