#! /bin/bash

file=$1
drive=$2

if [ -z "$file" ] ; then
  echo "usage: setup_grub image_file"
  exit 1
fi

if [ -z "$drive" ] ; then
  drive=0
fi

./mnt $file
mkdir -p /mnt/boot/grub
cp /usr/lib/grub/{fat_stage1_5,stage1,stage2} /mnt/boot/grub
cp /boot/vmlinuz /boot/initrd /boot/message /mnt/boot

sh -c 'cat >/mnt/boot/grub/menu.lst' <<zap
default 0
timeout 20
gfxmenu (hd${drive},0)/boot/message

title Test 1
  root (hd${drive},0)
  kernel /boot/vmlinuz vga=0x314 splash=silent showopts
  initrd /boot/initrd

title Test 2
  root (hd${drive},0)
  kernel /boot/vmlinuz vga=0x314 splash=silent showopts
  initrd /boot/initrd
zap

./umnt

echo "(hd0) /dev/null" >setup_grub.tmp
echo -e "device (hd${drive}) /mnt/boot.img\nsetup --prefix=/boot/grub (hd${drive}) (hd${drive},0)" | grub --batch  --device-map=setup_grub.tmp --no-config-file
rm -f setup_grub.tmp
